### PR TITLE
Add comments widget to 21ideas

### PR DESCRIPTION
**Pull request by fr4nzap**
Adding the zapthreads widget.

When running `hugo -D server` the "Log in" button does not appear - might have to do with Alby not working on `localhost`. It requires `hugo -D server -b https://new.21ideas.org --appendPort=false` but in that case livereload won't work. Not a big deal I think once integrated it can be tested on the actual https://new.21ideas.org

Draft PR until I fix an issue with publishing.

### CODE REVIEW

**Comment by bitcoin21ideas** [comment]
Thanks a lot for your time, @fr4nzap ! I'm wondering how logins will turn out here. On Habla we've got a login button on the website itself. I'm guessing some kind of Nostr login element will be needed. Or is it already integrated into zapthreads?

**Comment by fr4nzap** [comment]
@bitcoin21ideas dude I completely missed your message.

Yes zapthreads has an integrated login. Only if an `npub` is provided externally it will auto-login.

A few notes about the Hugo integration
 - Unlike Habla, which uses `naddr` as anchors, I am assuming that the reference here is the actual URL, correct? We can do that in nostr with an `r` tag. It's a bit inconvenient when testing because URLs change (localhost:1313, new.21ideas.org, www.21ideas.org) and comments are only associated with one URL. My suggestion for tests is tricking Hugo to serve the "good" domain so all comments go there
    - I used `hugo -D server -b https://www.21ideas.org --appendPort=false` so that all comments end up under the www domain
    - Reminder that you can pass `disable="publish:true"` to disable publishing for testing purposes (same for likes/zaps if you wanna disable, they are just counts for now)
 - It appears your search component listens for the key `S` to focus, which means it not possible to use that letter when writing a comment. Probably best to disable that
 - I had to remove the outline and made some minor styling improvements, feel free to change https://github.com/fr4nzap/zapthreads#css

Lmk how it goes!

**Comment by fr4nzap** [comment]
Other things coming soon:
 - keeping the login state when browsing different pages
 - multi language support

**Comment by bitcoin21ideas** [comment]
@mell4ce can you have a look into this please, especially the issue with the "s" and search.

**Comment by fr4nzap** [comment]
Do you also post these articles as long form notes? It occured to me that an option might be to then include the `naddr` as the article front-matter , and pass that to the `zap-threads` component. Would prevent potential issues with URL variations

**Comment by fr4nzap** [comment]
I commented out the line that enables the `S` search hotkey. It's a workaround which will have to be reapplied if you update the theme

**Pull request merged**
